[package]
name = "nokhwactl"
version = "0.10.0"
authors = ["l1npengtul <l1npengtul@protonmail.com>", "The Nokhwa Contributors"]
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["nokhwa/default"]

[dependencies]
ggez = "0.9.3"
flume = "0.11.0"
once_cell = "1.16.0"
color-eyre = "0.6.2"

[dependencies.ggez]
version = "0.8.1"
default-features = false

[dependencies.clap]
version = "4.0.20"
features = ["derive"]

# Use these as you need
[dependencies.nokhwa]
path = "../.."
features = ["input-native", "output-threaded"]

[dependencies.image]
version = "0.25.2"
features = ["png"]
