# Based on https://github.com/actions-rs/meta/blob/master/recipes/quickstart.md
#
# While our "example" application has the platform-specific code,
# for simplicity we are compiling and testing everything on the Ubuntu environment only.
# For multi-OS testing see the `cross.yml` workflow.
on:
  push:
    paths-ignore:
      - '*.md'
  pull_request: {}


name: Document All

# We specify the examples individually since they might need a different environment
jobs:
  docs:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt, clippy

      - name: Cargo Doc Core
        run: |
          cd nokhwa-core/
          cargo doc --features "test-fail-warnings, docs-features"

      - name: Cargo Doc Main Crate
        run: |
          cd ..
          cargo doc --features "test-fail-warning, docs-features, docs-nolink, docs-only"